//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.03 at 10:55:57 p. m. GMT-06:00 
//


package com.examenws.bm.schema;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.examenws.bm.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.examenws.bm.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InsertVentasRequest }
     * 
     */
    public InsertVentasRequest createInsertVentasRequest() {
        return new InsertVentasRequest();
    }

    /**
     * Create an instance of {@link ParametroIdCarrier }
     * 
     */
    public ParametroIdCarrier createParametroIdCarrier() {
        return new ParametroIdCarrier();
    }

    /**
     * Create an instance of {@link VoParametrosProdRs }
     * 
     */
    public VoParametrosProdRs createVoParametrosProdRs() {
        return new VoParametrosProdRs();
    }

    /**
     * Create an instance of {@link ParametroFechaHoy }
     * 
     */
    public ParametroFechaHoy createParametroFechaHoy() {
        return new ParametroFechaHoy();
    }

    /**
     * Create an instance of {@link VoParametrosProd }
     * 
     */
    public VoParametrosProd createVoParametrosProd() {
        return new VoParametrosProd();
    }

    /**
     * Create an instance of {@link VoHistoricoVentas }
     * 
     */
    public VoHistoricoVentas createVoHistoricoVentas() {
        return new VoHistoricoVentas();
    }

    /**
     * Create an instance of {@link ParametroIdMonto }
     * 
     */
    public ParametroIdMonto createParametroIdMonto() {
        return new ParametroIdMonto();
    }

    /**
     * Create an instance of {@link StatusInsert }
     * 
     */
    public StatusInsert createStatusInsert() {
        return new StatusInsert();
    }

    /**
     * Create an instance of {@link ObtenMontoPorCarrierRequest }
     * 
     */
    public ObtenMontoPorCarrierRequest createObtenMontoPorCarrierRequest() {
        return new ObtenMontoPorCarrierRequest();
    }

    /**
     * Create an instance of {@link ObtenVentasPorMontoRequest }
     * 
     */
    public ObtenVentasPorMontoRequest createObtenVentasPorMontoRequest() {
        return new ObtenVentasPorMontoRequest();
    }

    /**
     * Create an instance of {@link ObtenTotalVentasRequest }
     * 
     */
    public ObtenTotalVentasRequest createObtenTotalVentasRequest() {
        return new ObtenTotalVentasRequest();
    }

    /**
     * Create an instance of {@link ListVoParametrosProd }
     * 
     */
    public ListVoParametrosProd createListVoParametrosProd() {
        return new ListVoParametrosProd();
    }

}
