//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.03 at 10:55:57 p. m. GMT-06:00 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://examenws.com/bm/schema", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.examenws.bm.schema;
