//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.03 at 10:55:57 p. m. GMT-06:00 
//


package com.examenws.bm.schema;

import javax.xml.datatype.XMLGregorianCalendar;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for voHistoricoVentas complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="voHistoricoVentas">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id_hist_vent" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="id_proveedor" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="id_pagos" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="telefono" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fch_creacion" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "voHistoricoVentas", propOrder = {
    "idHistVent",
    "idProveedor",
    "idPagos",
    "telefono",
    "fchCreacion"
})
public class VoHistoricoVentas {

    @XmlElement(name = "id_hist_vent")
    protected int idHistVent;
    @XmlElement(name = "id_proveedor")
    protected int idProveedor;
    @XmlElement(name = "id_pagos")
    protected int idPagos;
    @XmlElement(required = true)
    protected String telefono;
    @XmlElement(name = "fch_creacion", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fchCreacion;

    /**
     * Gets the value of the idHistVent property.
     * 
     */
    public int getIdHistVent() {
        return idHistVent;
    }

    /**
     * Sets the value of the idHistVent property.
     * 
     */
    public void setIdHistVent(int value) {
        this.idHistVent = value;
    }

    /**
     * Gets the value of the idProveedor property.
     * 
     */
    public int getIdProveedor() {
        return idProveedor;
    }

    /**
     * Sets the value of the idProveedor property.
     * 
     */
    public void setIdProveedor(int value) {
        this.idProveedor = value;
    }

    /**
     * Gets the value of the idPagos property.
     * 
     */
    public int getIdPagos() {
        return idPagos;
    }

    /**
     * Sets the value of the idPagos property.
     * 
     */
    public void setIdPagos(int value) {
        this.idPagos = value;
    }

    /**
     * Gets the value of the telefono property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * Sets the value of the telefono property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefono(String value) {
        this.telefono = value;
    }

    /**
     * Gets the value of the fchCreacion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFchCreacion() {
        return fchCreacion;
    }

    /**
     * Sets the value of the fchCreacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFchCreacion(XMLGregorianCalendar value) {
        this.fchCreacion = value;
    }

}
