#Query creacion de Tablas en MySQL

#***********************************
#**PROVEEDOR**

CREATE TABLE `examen`.`C_PROVEEDOR`
(
  `ID_PROVEEDOR`	MEDIUMINT NOT NULL AUTO_INCREMENT,
  `NOMBRE_PROV`		VARCHAR(30),
  `DESCRIPCION`		VARCHAR(100),
  PRIMARY KEY (`ID_PROVEEDOR`));

#***********************************
#**PAGOS**

CREATE TABLE `examen`.`C_PAGOS` (
  `ID_PAGOS` INT NOT NULL AUTO_INCREMENT,
  `MONTO`	INT NULL,
  `DESCRIPCION` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_PAGOS`));

#***********************************
#**PLANES**

CREATE TABLE `examen`.`T_PLANES`
(
  `ID_PLANES`		MEDIUMINT NOT NULL AUTO_INCREMENT,
  `ID_PROVEEDOR`	MEDIUMINT,
  `ID_PAGOS`		MEDIUMINT,
  PRIMARY KEY (`ID_PLANES`));


#***********************************
#**HISTORICO DE VENTAS**

CREATE TABLE `examen`.`T_HISTORICO_VENTAS`
(
  `ID_HIST_VENT`	MEDIUMINT NOT NULL AUTO_INCREMENT,
  `ID_PROVEEDOR`	MEDIUMINT,
  `ID_PAGOS`		MEDIUMINT,
  `TELEFONO`		VARCHAR(30),
  `FCH_CREACION`	DATETIME,
  PRIMARY KEY (`ID_HIST_VENT`));