#***************************************************************************************************************

#CARGA INICIAL

INSERT INTO `examen`.`C_PROVEEDOR` (ID_PROVEEDOR, NOMBRE_PROV, DESCRIPCION) VALUES (NULL, 'TELCEL', 'EMPRESA TELCEL' );
INSERT INTO `examen`.`C_PROVEEDOR` (ID_PROVEEDOR, NOMBRE_PROV, DESCRIPCION) VALUES (NULL, 'PILLOFON', 'EMPRESA PILLOFON' );
INSERT INTO `examen`.`C_PROVEEDOR` (ID_PROVEEDOR, NOMBRE_PROV, DESCRIPCION) VALUES (NULL, 'ATT', 'EMPRESA ATT' );
INSERT INTO `examen`.`C_PROVEEDOR` (ID_PROVEEDOR, NOMBRE_PROV, DESCRIPCION) VALUES (NULL, 'MOVISTAR', 'EMPRESA ALCATEL' );


INSERT INTO `examen`.`c_pagos` (ID_PAGOS, MONTO, DESCRIPCION) VALUES (NULL, 10, 'Paquete $10' );
INSERT INTO `examen`.`c_pagos` (ID_PAGOS, MONTO, DESCRIPCION) VALUES (NULL, 30, 'Paquete $30' );
INSERT INTO `examen`.`c_pagos` (ID_PAGOS, MONTO, DESCRIPCION) VALUES (NULL, 50, 'Paquete $50' );
INSERT INTO `examen`.`c_pagos` (ID_PAGOS, MONTO, DESCRIPCION) VALUES (NULL, 100, 'Paquete $100' );
INSERT INTO `examen`.`c_pagos` (ID_PAGOS, MONTO, DESCRIPCION) VALUES (NULL, 150, 'Paquete $150' );
INSERT INTO `examen`.`c_pagos` (ID_PAGOS, MONTO, DESCRIPCION) VALUES (NULL, 200, 'Paquete $200' );
INSERT INTO `examen`.`c_pagos` (ID_PAGOS, MONTO, DESCRIPCION) VALUES (NULL, 300, 'Paquete $300' );
INSERT INTO `examen`.`c_pagos` (ID_PAGOS, MONTO, DESCRIPCION) VALUES (NULL, 500, 'Paquete $500' );

INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 1, 1 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 1, 2 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 1, 3 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 1, 4 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 1, 5 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 1, 6 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 1, 7 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 1, 8 );

INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 2, 1 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 2, 2 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 2, 3 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 2, 4 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 2, 5 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 2, 6 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 2, 7 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 2, 8 );

INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 3, 1 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 3, 2 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 3, 3 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 3, 4 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 3, 5 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 3, 6 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 3, 7 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 3, 8 );

INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 4, 1 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 4, 2 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 4, 3 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 4, 4 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 4, 5 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 4, 6 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 4, 7 );
INSERT INTO `examen`.`T_PLANES` (ID_PLANES, ID_PROVEEDOR, ID_PAGOS) VALUES (NULL, 4, 8 );


#***************************************************************************************************************
#Datos de prueba
#***************************************************************************************************************

INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 1, 4, '5544332211', NOW() - INTERVAL 3 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 2, 2, '5511223344', NOW() - INTERVAL 3 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 3, 4, '5512345678', NOW() - INTERVAL 3 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 1, 3, '5544332211', NOW() - INTERVAL 3 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 2, 4, '5512345678', NOW() - INTERVAL 3 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 3, 3, '5511223344', NOW() - INTERVAL 3 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 4, 4, '5512345678', NOW() - INTERVAL 3 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 1, 1, '5544332211', NOW() - INTERVAL 3 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 2, 2, '5511223344', NOW() - INTERVAL 3 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 3, 4, '5555555555', NOW() - INTERVAL 3 DAY );

INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 1, 6, '5544332211', NOW() - INTERVAL 2 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 2, 2, '5512345678', NOW() - INTERVAL 2 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 3, 4, '5511223344', NOW() - INTERVAL 2 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 4, 3, '5555555555', NOW() - INTERVAL 2 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 1, 4, '5544332211', NOW() - INTERVAL 2 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 2, 3, '5512345678', NOW() - INTERVAL 2 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 3, 4, '5544332211', NOW() - INTERVAL 2 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 4, 1, '5511223344', NOW() - INTERVAL 2 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 1, 2, '5555555555', NOW() - INTERVAL 2 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 2, 5, '5544332211', NOW() - INTERVAL 2 DAY );

INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 4, 1, '5544332211', NOW() - INTERVAL 1 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 3, 4, '5512345678', NOW() - INTERVAL 1 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 2, 4, '5544332211', NOW() - INTERVAL 1 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 1, 1, '5511223344', NOW() - INTERVAL 1 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 4, 4, '5512345678', NOW() - INTERVAL 1 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 3, 3, '5544332211', NOW() - INTERVAL 1 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 2, 6, '5512345678', NOW() - INTERVAL 1 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 1, 5, '5511223344', NOW() - INTERVAL 1 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 1, 2, '5555555555', NOW() - INTERVAL 1 DAY );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 2, 4, '5544332211', NOW() - INTERVAL 1 DAY );

INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 1, 4, '5544332211', NOW() );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 2, 4, '5512345678', NOW() );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 3, 4, '5511223344', NOW() );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 4, 1, '5555555555', NOW() );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 1, 1, '5544332211', NOW() );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 2, 3, '5511223344', NOW() );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 3, 4, '5544332211', NOW() );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 4, 5, '5512345678', NOW() );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 1, 8, '5511223344', NOW() );
INSERT INTO `examen`.`T_HISTORICO_VENTAS` (ID_HIST_VENT, ID_PROVEEDOR, ID_PAGOS, TELEFONO, FCH_CREACION) VALUES (NULL, 2, 7, '5555555555', NOW() );